### ISSUE TITLE
Can't connect to webUI

### ISSUE THREAD

**Issue by schmunk42** [ahannigan/docker-arachni#3]
When starting the web_ui it looks like `Puma` is listening to `localhost:9292`, which makes it unaccessible in the Docker container.

Did this behavior change? It was working with a previous version AFAIR.

Related: http://stackoverflow.com/a/28078966/291573

**Comment by schmunk42** [comment]
As a workaround, I was able to build a working image with:

```
docker build --build-arg VERSION=1.2.1 --build-arg WEB_VERSION=0.5.7.1 -t arachni:1.2.1-0.5.7.1 .
```

**Comment by ahannigan** [comment]
fixed, thanks for the tip
